spring:
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: info
server:
  port: ${PORT}